// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionData.Context;

#nullable disable

namespace SistemaGestionData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240212162100_AddedIdentityId")]
    partial class AddedIdentityId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaGestionEntities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Costo = 175.98m,
                            Descripcion = "Microondas",
                            IdUsuario = 10,
                            PrecioVenta = 543.11m,
                            Stock = 333
                        },
                        new
                        {
                            Id = 2,
                            Costo = 281.75m,
                            Descripcion = "Heladera",
                            IdUsuario = 4,
                            PrecioVenta = 830.27m,
                            Stock = 108
                        },
                        new
                        {
                            Id = 3,
                            Costo = 236.55m,
                            Descripcion = "Cama",
                            IdUsuario = 7,
                            PrecioVenta = 848.15m,
                            Stock = 323
                        },
                        new
                        {
                            Id = 4,
                            Costo = 119.28m,
                            Descripcion = "TV",
                            IdUsuario = 4,
                            PrecioVenta = 562.01m,
                            Stock = 313
                        },
                        new
                        {
                            Id = 5,
                            Costo = 224.72m,
                            Descripcion = "Notebook HP",
                            IdUsuario = 10,
                            PrecioVenta = 894.97m,
                            Stock = 207
                        },
                        new
                        {
                            Id = 6,
                            Costo = 137.36m,
                            Descripcion = "Cocina",
                            IdUsuario = 9,
                            PrecioVenta = 507.0m,
                            Stock = 39
                        },
                        new
                        {
                            Id = 7,
                            Costo = 230.29m,
                            Descripcion = "Parrilla",
                            IdUsuario = 7,
                            PrecioVenta = 486.16m,
                            Stock = 283
                        },
                        new
                        {
                            Id = 8,
                            Costo = 189.95m,
                            Descripcion = "Auriculares",
                            IdUsuario = 6,
                            PrecioVenta = 961.61m,
                            Stock = 119
                        },
                        new
                        {
                            Id = 9,
                            Costo = 180.22m,
                            Descripcion = "Celular",
                            IdUsuario = 7,
                            PrecioVenta = 589.88m,
                            Stock = 316
                        },
                        new
                        {
                            Id = 10,
                            Costo = 180.22m,
                            Descripcion = "Escritorio de PC",
                            IdUsuario = 10,
                            PrecioVenta = 531.02m,
                            Stock = 208
                        });
                });

            modelBuilder.Entity("SistemaGestionEntities.ProductoVendido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("ProductosVendidos");
                });

            modelBuilder.Entity("SistemaGestionEntities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Brignall",
                            Contrasenia = "sC6%bv.1cQ1.p4IX",
                            Mail = "jbrignall0@timesonline.co.uk",
                            Nombre = "Jae",
                            NombreUsuario = "jbrignall0"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Santora",
                            Contrasenia = "wG9@\\XLplgECZN{",
                            Mail = "dsantora1@blogspot.com",
                            Nombre = "Darci",
                            NombreUsuario = "dsantora1"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Godsmark",
                            Contrasenia = "rO5}&C$$<e\"$",
                            Mail = "lgodsmark2@taobao.com",
                            Nombre = "Linea",
                            NombreUsuario = "lgodsmark2"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Gaine",
                            Contrasenia = "eJ8($/R5*@",
                            Mail = "fgaine3@baidu.com",
                            Nombre = "Faun",
                            NombreUsuario = "fgaine3"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Indgs",
                            Contrasenia = "dF5!$f*)P",
                            Mail = "mindgs4@senate.gov",
                            Nombre = "Matt",
                            NombreUsuario = "mindgs4"
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "Dyers",
                            Contrasenia = "fR9@9v%S?D03N(9b",
                            Mail = "hdyers5@nature.com",
                            Nombre = "Hertha",
                            NombreUsuario = "hdyers5"
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "Cadigan",
                            Contrasenia = "uU1#&P3J",
                            Mail = "mcadigan6@123-reg.co.uk",
                            Nombre = "Myrta",
                            NombreUsuario = "mcadigan6"
                        },
                        new
                        {
                            Id = 8,
                            Apellido = "Cran",
                            Contrasenia = "cE6#lOe63p",
                            Mail = "ccran7@ow.ly",
                            Nombre = "Carling",
                            NombreUsuario = "ccran7"
                        },
                        new
                        {
                            Id = 9,
                            Apellido = "Gilroy",
                            Contrasenia = "lW6\\w%5818g",
                            Mail = "fgilroy8@liveinternet.ru",
                            Nombre = "Felicity",
                            NombreUsuario = "fgilroy8"
                        },
                        new
                        {
                            Id = 10,
                            Apellido = "Grosvenor",
                            Contrasenia = "lU9''v`cO",
                            Mail = "mgrosvenor9@nature.com",
                            Nombre = "Marnie",
                            NombreUsuario = "mgrosvenor9"
                        });
                });

            modelBuilder.Entity("SistemaGestionEntities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("SistemaGestionEntities.Producto", b =>
                {
                    b.HasOne("SistemaGestionEntities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionEntities.ProductoVendido", b =>
                {
                    b.HasOne("SistemaGestionEntities.Producto", "Producto")
                        .WithMany("ProductosVendidos")
                        .HasForeignKey("ProductoId");

                    b.HasOne("SistemaGestionEntities.Venta", "Venta")
                        .WithMany("ProductosVendidos")
                        .HasForeignKey("VentaId");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SistemaGestionEntities.Venta", b =>
                {
                    b.HasOne("SistemaGestionEntities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionEntities.Producto", b =>
                {
                    b.Navigation("ProductosVendidos");
                });

            modelBuilder.Entity("SistemaGestionEntities.Venta", b =>
                {
                    b.Navigation("ProductosVendidos");
                });
#pragma warning restore 612, 618
        }
    }
}
